spring.application.name=cafebrew

#------------------------

# Database (Railway - use ENV variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#---------------------------------------------------------------

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret Key (Should be at least 256 bits, this is a base64 encoded strong key)
# For production use, you should keep this in environment variables.
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000

# Thymeleaf Cache (disable for dev)
spring.thymeleaf.cache=false

# Razorpay Configuration
# Replace these with real keys when going to production.
# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
